from .label_smoothed_cross_entropy_with_entity_contrastive import LabelSmoothedCrossEntropyCriterionWithEntityContrastive
from .label_smoothed_cross_entropy_with_multi_granularity_contrastive import LabelSmoothedCrossEntropyCriterionWithEntityContrastive
from .label_smoothed_cross_entropy_with_contrastive import LabelSmoothedCrossEntropyCriterionWithContrastive